image:
  file: .gitpod.Dockerfile

# so far, this project doesn't have ports
# ports:
#     - port: 3000
#       onOpen: open-preview
tasks:
    - before: >
        export PIP_USER=no &&
        poetry config virtualenvs.in-project true && 
        poetry install
    - command: >
        echo "sleeping to allow 30s to install dependancies..." &&
        sleep 30s &&
        poetry shell
# vscode:
#   extensions:
#     - littlefoxteam.vscode-python-test-adapter@0.6.6:dFrDC47V32ioT4mq1YZKPg==